Repository yeldiRium/st3k101, pull requests merged in 2018-10, with the labels that each got.

#41 [BUGFIX] close modal on session changes
  frontend/src/Plugins/LoadingSpinnerModal/LoadingSpinnerModal.vue
  frontend/src/components/App.vue
  frontend/src/components/Partials/Modal/ClosableModal.vue
  frontend/src/components/Partials/Modal/CreateDimension.vue
  frontend/src/components/Partials/Modal/CreateQuestion.vue
  frontend/src/components/Partials/Modal/CreateQuestionnaire.vue
  frontend/src/components/Partials/Modal/CreateResource.vue
  frontend/src/components/Partials/Modal/Dialog.vue
  frontend/src/components/Partials/Modal/TranslateDimension.vue
  frontend/src/components/Partials/Modal/TranslateQuestion.vue
  frontend/src/components/Partials/Modal/TranslateQuestionnaire.vue
  frontend/src/components/Partials/Modal/TranslateResource.vue
  frontend/src/components/Partials/Modal/UseDimensionTemplate.vue
  frontend/src/components/Partials/Modal/UseQuestionTemplate.vue
  frontend/src/components/Partials/Modal/UseQuestionnaireTemplate.vue
  nginx/nginx.conf
Labels: bug

#38 [BUGFIX] fix check for master branch in circleci config
  .circleci/config.yml
Labels: bug

#72 [Bugfix] grid safari
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Partials/Form/Button.vue
  frontend/src/components/Partials/Modal/CreateResource.vue
Labels: bug

#74 clean up stuff
  frontend/package.json
  frontend/src/Plugins/HandleApiError/index.js
  frontend/src/Plugins/LoadingSpinnerModal/index.js
  frontend/src/api/Dimension.js
  frontend/src/api/Question.js
  frontend/src/api/Questionnaire.js
  frontend/src/api/Util/Parse.js
  frontend/src/api/Util/Request.js
  frontend/src/api/Util/Response.js
  frontend/src/components/Partials/List/FuzzySearchableList.vue
  frontend/src/components/Partials/Modal/CreateResource.vue
  frontend/src/components/Partials/Modal/TranslateResource.vue
  frontend/src/components/Partials/Modal/UpdateAllRangeLabels.vue
  frontend/src/components/Partials/SurveyBase/Challenge/EMailListForm.vue
  frontend/src/components/Partials/SurveyBase/Challenge/PasswordForm.vue
  frontend/src/components/Partials/SurveyBase/Config/RangeSVG.vue
  frontend/src/components/Partials/SurveyBase/Dimension.vue
  frontend/src/components/Partials/SurveyBase/Question.vue
  frontend/src/components/Partials/SurveyBase/Questionnaire.vue
  frontend/src/components/Partials/SurveyBase/SurveyBase.vue
  frontend/src/components/Partials/SurveyBase/TrackerEntries.vue
  frontend/src/components/Views/Embedded/EmbeddedSurveyForSubmission.vue
  frontend/src/components/Views/Private/Account.vue
  frontend/src/components/Views/Private/Dashboard.vue
  frontend/src/components/Views/Public/Authentication.vue
  frontend/src/components/Views/Public/SurveyForSubmission.vue
  frontend/src/express/embeddedAuthenticationMiddleware.js
  frontend/src/index.html
  frontend/src/model/OwnedResource.js
  frontend/src/model/SurveyBase/Challenge/EMailBlacklist.js
  frontend/src/model/SurveyBase/Challenge/EMailListBase.js
  frontend/src/model/SurveyBase/Challenge/EMailWhitelist.js
  frontend/src/model/SurveyBase/Dimension.js
  frontend/src/model/SurveyBase/Question.js
  frontend/src/model/TrackerEntry.js
  frontend/src/store/Utility/cookies.js
  frontend/src/store/index.js
  frontend/src/store/modules/Dimensions.js
  frontend/src/store/modules/Language.js
  frontend/src/store/modules/Questionnaires.js
  frontend/src/store/modules/Questions.js
  frontend/src/store/modules/Session.js
  frontend/src/store/modules/Statistics.js
  frontend/src/store/modules/Submission.js
  frontend/src/store/modules/TrackerEntries.js
Labels: enhancement

#84 [BUGFIX] Make ShadowQuestionnaire.accepts_submissions updatable
  backend/app/api/Questionnaire.py
Labels: bug

#83 [BUGFIX] backend: various fixes in submission & verification logic
  backend/app/api/Response.py
  backend/app/framework/email.py
  backend/app/model/models/Question.py
  backend/app/model/models/QuestionResponse.py
Labels: bug

#85 [BUGFIX] sort DimensionForm by Question.position
  frontend/src/components/Partials/SurveyBase/Submission/DimensionForm.vue
Labels: bug

#88 [BUGFIX] descriptive api errors in submission
  backend/app/api/Response.py
Labels: bug, enhancement

#94 [BUGFIX] xapi-publisher: improved error handling
  xapi-publisher/app/main.py
Labels: bug

#99 [TASK] Add Tests for Response.js
  frontend/src/api/Util/Response.js
  frontend/src/api/Util/__tests__/Response.js
  frontend/src/api/Util/renameProp.js
  frontend/src/express/embeddedAuthenticationMiddleware.js
Labels: enhancement

#100 [TASK] add unit-tests for parser functions
  frontend/src/api/Errors/index.js
  frontend/src/api/Util/Parse.js
  frontend/src/api/Util/__tests__/Parse.js
  frontend/src/api/Util/__tests__/__snapshots__/Parse.js.snap
Labels: enhancement

#101 [BUGFIX] log application errors
  backend/app/app.py
  backend/app/framework/logging.py
  backend/app/main.py
  backend/app/model/models/DataClient.py
  backend/app/model/models/DataSubject.py
Labels: bug, enhancement

#102 [FEATURE] Authentication handling in xapi-publisher
  xapi-publisher/Dockerfile
  xapi-publisher/app/api.py
  xapi-publisher/app/app.py
  xapi-publisher/app/authentication/SharedReusableSession.py
  xapi-publisher/app/authentication/__init__.py
  xapi-publisher/app/authentication/methods/AuthenticationMethod.py
  xapi-publisher/app/authentication/methods/NoAuthentication.py
  xapi-publisher/app/authentication/methods/TLAFactsEngine.py
  xapi-publisher/app/authentication/methods/__init__.py
  xapi-publisher/app/business_logic.py
  xapi-publisher/app/flask.cfg
  xapi-publisher/app/main.py
  xapi-publisher/app/transmission.py
Labels: enhancement

#107 [FIX] use QuestionResponse.id to identify xapi statements
  backend/app/api/Response.py
  backend/app/framework/signals.py
  backend/app/framework/xapi/signals.py
Labels: bug
